### ISSUE TITLE
Highlights don't show right after exiting Insert mode

### ISSUE THREAD

**Issue by YaLTeR** [joshestein/ideavim-quickscope#11]
When I type something in Insert mode (which hides the highlights) and press Esc to go back to Normal mode, the highlights don't show until another cursor movement. Which means that you cannot see the highlights to quickly f/F/t/T right after typing in Insert mode.

**Comment by joshestein** [comment]
Unfortunately, there is not yet a way to detect when a user has switched from insert to normal mode (and vice versa). This forces us to listen for a new caret event before seeing/removing highlights. Once [autocommands are implemented](https://youtrack.jetbrains.com/issue/VIM-1693/Add-support-for-autocmd) we should be able to fix this.

Please see https://github.com/joshestein/ideavim-quickscope/issues/7 for a more detailed discussion.

**Comment by joshestein** [comment]
Unfortunately, there is not yet a way to detect when a user has switched from insert to normal mode (and vice versa). This forces us to listen for a new caret event before seeing/removing highlights. Once [autocommands are implemented](https://youtrack.jetbrains.com/issue/VIM-1693/Add-support-for-autocmd) we should be able to fix this.

Please see https://github.com/joshestein/ideavim-quickscope/issues/7 for a more detailed discussion.

**Comment by stutterrrrer** [comment]
waiting on fix

**Comment by joshestein** [comment]
Hi @stutterrrrer. Please see my previous comment. Closing as we cannot fix this until autocommands are implemented in IdeaVim.
