### ISSUE TITLE
Is there a way to disable it for Diff View?

### ISSUE THREAD

**Issue by TimShilov** [joshestein/ideavim-quickscope#14]
First of all, thanks for the great plugin!

However, there's one annoyance that bugs me. When you watch diff during commit, the plugin highlights letters even when my cursor is not even in the editor.
I usually use arrows in Commit tool window to go between files and Space to stage them. So having highlighting in Diff serves no purpose and just makes diffs harder to read.

Is there any way to disable this?

<img width="1183" alt="Screenshot 2024-04-07 at 21 20 53" src="https://github.com/joshestein/ideavim-quickscope/assets/20239045/1744bee6-6c68-4370-b89f-d52734c0c049">

**Comment by joshestein** [comment]
Thanks for your interest in the plugin 😄 

I've changed this as part of https://github.com/joshestein/ideavim-quickscope/commit/dd74a028929463658205255b359e9fb51f9ccb6a. After the latest version is released (usually takes a few days for approval) you can use `let g:qs_disable_for_diffs = 1`.

**Comment by joshestein** [comment]
@TimShilov I'm going to close this as the new update has been released. If the problem persists feel free to open another issue.
