### ISSUE TITLE
Feature request: change foreground not background colour

### ISSUE THREAD

**Issue by james-skinner-deltatre** [joshestein/ideavim-quickscope#4]
Thanks again for this plugin 👍🏼 

Would be cool if the highlight changed the text colour rather than background. Why? Its less intrusive and easier to read imo

Current behaviour:
<img width="472" alt="Screenshot 2022-11-22 at 11 44 34" src="https://user-images.githubusercontent.com/74296503/203305993-402424e5-67f6-463a-813a-a66e6c923ccb.png">

Suggestion (this is quick-scope in nvim):
<img width="472" alt="Screenshot 2022-11-22 at 11 45 00" src="https://user-images.githubusercontent.com/74296503/203306059-9868a003-b6c9-4d0d-add9-a681eb655f1e.png">

**Comment by joshestein** [comment]
Thank you for the suggestion! I've updated and pushed a new version (1.0.6). By default, it looks something like this:

![image](https://user-images.githubusercontent.com/27491286/203404786-154220dd-41c3-43b3-af8a-e351aee1038d.png)

I've introduced two new variables `g:qs_primary_color` and `g:qs_secondary_color` you can use to override the defaults. For example, putting `let g:qs_primary_color="#ff0000"` in your `.ideavimrc` should set the primary color to red. Both parameters require a hex string to work correctly.

I would've preferred to stick to the original plugin syntax, but can't seem to find support for highlight groups in IdeaVim.

Let me know if you there are any problems with how this works!
