### ISSUE TITLE
Is `g:qs_accepted_chars` configurable?

### ISSUE THREAD

**Issue by sgoudham** [joshestein/ideavim-quickscope#5]
Hi :wave:, thank you for porting this to Intellij, it looks great!

I was wondering if the `g:qs_accepted_chars` option that exists within the original [quicksope](https://github.com/unblevable/quick-scope#accepted-characters) plugin is configurable in this port.

**Comment by sgoudham** [comment]
I had a quick look at the code to see if I could deduce it myself, and I found that the [ACCEPTED_CHARS](https://github.com/joshestein/ideavim-quickscope/blob/871983e2588831fd5ca823c9b9a0f5389088115a/src/main/kotlin/com/joshestein/ideavimquickscope/IdeaVimQuickscopeExtension.kt#L23) variable is defined but doesn't seem to be exposed for the user to configure it.

**Comment by joshestein** [comment]
Thank you for the suggestion, and the PR! I'm pushing the new version to the marketplace now, which will hopefully be approved and released in the next few days :tada:
